SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT B.ITEM_ID
                 FROM ITEM_INFO AS A, ITEM_TREE AS B
                 WHERE A.ITEM_ID = B.PARENT_ITEM_ID
                 AND A.RARITY = 'RARE')
ORDER BY ITEM_ID DESC;
