-- 코드를 작성해주세요
SELECT COUNT(ID) AS FISH_COUNT
FROM FISH_INFO
WHERE FISH_TYPE IN (SELECT B.FISH_TYPE
       FROM FISH_INFO AS A, FISH_NAME_INFO AS B
       WHERE A.FISH_TYPE = B.FISH_TYPE
       AND FISH_NAME IN ('BASS', 'SNAPPER'));